---
timezone: America/Chicago
url: null
include:
  - _pages
  - _data
  - _plugins
  - _trailers
  - _trailer_type
sitename: Capital Leasing
relative_permalinks: false
favicon: null
lang: en
author: null
disqus: null
google_analytics: G-YPCZ6WF5GY
social:
  name: Capital Leasing
  links:
    - null
logo: null
locale: en_us
collections:
  products:
    output: true
  trailers:
    output: true
  trailer_type:
    output: true
defaults:
  - scope:
      path: ""
    values:
      layout: default
      _options:
        content:
          uploads_dir: uploads/:title
          format: p h1 h2 h3 h4 h5 h6 div
          styles: /assets/css/theme.css
          undo: true
          redo: true
          left: text-left
          center: text-center
          right: text-right
          justify: justify-content-center
          bold: true
          italic: true
          underline: true
          strike: true
          subscript: false
          superscript: false
          blockquote: true
          table: true
          copyformatting: true
          removeformat: true
          numberedlist: true
          bulletedlist: true
          outdent: false
          indent: false
          image: true
          link: true
          embed: true
  - scope:
      path: ""
      type: products
    values:
      layout: product
  - scope:
      type: pages
      path: _pages/index.html
    values:
      permalink: null
  - scope:
      type: data
      path: data
    values:
      permalink: null
  - scope:
      type: posts
    values:
      layout: bloglayout
permalink: /:title/
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-assets
exclude:
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _site
