_schema: _schema
paths:
  uploads: uploads
  uploads_use_relative_path: false
  static: ''
  dam_uploads: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes

collections_config:
  data:
    path: _data
    icon: data_usage
    output: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false

  pages:
    path: ''
    icon: notes
    output: true
    filter: strict
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false

  trailers:
    path: _trailers
    name: Trailers For Sale
    icon: rv_hookup
    output: true
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/trailers.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes

collections_config_override: true

_inputs:
  # Hidden/system
  layout:
    type: auto
    hidden: true
    cascade: true

  # Simple arrays (strings) — use entry type keys
  highlighted_features:
    type: array
    label: Highlighted Features
  highlighted_features[*]:
    type: text

  trailer:
    type: array
    label: Trailer Features
  trailer[*]:
    type: text

  living_quarters:
    type: array
    label: Living Quarter Features
  living_quarters[*]:
    type: text

  # Structured array (objects)
  additional_specs:
    type: array
    label: Additional Specifications
    options:
      structures: _structures.additional_spec

  # Selects
  trailer_type:
    type: select
    options:
      allow_empty: true
      values:
        - Living Quarters
        - Non-Living Quarters
        - Cargo and Specialty
    label: Trailer Type

  condition:
    type: select
    options:
      allow_empty: true
      values:
        - New
        - Used

  hitch_type:
    type: select
    options:
      allow_empty: true
      values:
        - Gooseneck
        - Bumper pull
    label: Hitch Type

  # Misc inputs
  vin:
    type: text
    label: VIN Number
  color:
    type: text
    label: Trailer Color
  thumb:
    type: image
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
  featured:
    type: switch
    label: Feature on Home Page

# Define structures used by arrays above
_structures:
  additional_spec:
    values:
      - value:
          spec_title:
          spec:

_select_data:
  jekyll-archives:
    layout: archive
    enabled: []
    permalinks:
      year: /:year/
      month: /:year/:month/
      day: /:year/:month/:day/
      tag: /tag/:name/
      category: /category/:name/

source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true

timezone: America/Chicago
