_schema: _schema
paths:
  uploads: uploads
  uploads_use_relative_path: false
  static: ''
  dam_uploads: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes

collections_config:
  data:
    path: _data
    icon: data_usage
    output: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: ''
    icon: notes
    output: true
    filter: strict
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  Trailer Types:
    path: _trailer_type
    name: Trailer Types
    icon: category
    output: false
    _enabled_editors:
      - data
    _structures:
      featured:
        - label: Featured on the home page
          _inputs:
            type:
              type: auto
              cascade: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  trailers:
    path: _trailers
    name: Trailers For Sale
    icon: rv_hookup
    output: true
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/trailers.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes

collections_config_override: true

_inputs:
  layout:
    type: auto
    hidden: true
    cascade: true

  height:
    type: text
    cascade: true

  width:
    type: text
    cascade: true

  length:
    type: text
    cascade: true

  trailer_type:
    type: select
    options:
      allow_empty: true
      values:
        - Living Quarters
        - Non-Living Quarters
        - Cargo and Specialty
    label: Trailer Type
    cascade: false

  condition:
    type: select
    options:
      allow_empty: true
      values:
        - New
        - Used
    cascade: true

  hitch_type:
    type: select
    options:
      allow_empty: true
      values:
        - Gooseneck
        - Bumper pull
    label: Hitch Type
    cascade: true

  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true

  # ===== FIXED ARRAY + STRUCTURE FIELDS =====

  additional_specs:
    type: array
    label: Additional Specifications
    options:
      add_button_label: Add specification
      structures:
        - label: Specification
          preview:
            text: "{{ spec_title | default: 'Untitled Specification' }}"
          values:
            spec_title:
              type: text
              label: Specification Title
            spec:
              type: text
              label: Specification

  highlighted_features:
    type: array
    label: Highlighted Features
    options:
      add_button_label: Add feature
      type: text
      placeholder: e.g. 13ft 8in Short Wall

  trailer:
    type: array
    label: Trailer Features
    options:
      add_button_label: Add feature
      type: text
      placeholder: e.g. Stud Divider

  living_quarters:
    type: array
    label: Living Quarter Features
    options:
      add_button_label: Add feature
      type: text
      placeholder: e.g. Leather Sofa

  gallery:
    type: array
    label: Images
    options:
      add_button_label: Add image
      structures:
        - label: Image
          preview:
            text: "{{ image | split: '/' | last }}"
            subtext: Image
          values:
            image:
              type: image
              label: Image

  video:
    type: array
    label: Video
    options:
      add_button_label: Add video
      structures:
        - label: Video
          preview:
            text: "{{ url }}"
            subtext: "{{ thumb | split: '/' | last }}"
          values:
            url:
              type: url
              label: Video URL
            thumb:
              type: image
              label: Thumbnail

  vin:
    type: text
    options:
      empty_type: string
    label: VIN Number
    cascade: true

  color:
    type: text
    label: Trailer Color
    cascade: true

  thumb:
    type: image
    cascade: true

  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true

  featured:
    type: switch
    label: Feature on Home Page
    cascade: true

  Image:
    type: image
    cascade: true

_select_data:
  social:
    name: Capital Leasing
    links: []
  jekyll-archives:
    layout: archive
    enabled: []
    permalinks:
      year: /:year/
      month: /:year/:month/
      day: /:year/:month/:day/
      tag: /tag/:name/
      category: /category/:name/
  archives: []

source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true

timezone: America/Chicago
