_schema: _schema
paths:
  uploads: uploads
  uploads_use_relative_path: false
  static: ''
  dam_uploads: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes

collections_config:
  data:
    path: _data
    icon: data_usage
    output: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false

  pages:
    path: ''
    icon: notes
    output: true
    filter: strict
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false

  trailers:
    path: _trailers
    name: Trailers For Sale
    icon: rv_hookup
    output: true
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/trailers.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes

collections_config_override: true

_inputs:
  layout:
    type: auto
    hidden: true
    cascade: true

  trailer_type:
    type: select
    options:
      allow_empty: true
      values:
        - Living Quarters
        - Non-Living Quarters
        - Cargo and Specialty
    label: Trailer Type

  condition:
    type: select
    options:
      allow_empty: true
      values:
        - New
        - Used

  hitch_type:
    type: select
    options:
      allow_empty: true
      values:
        - Gooseneck
        - Bumper pull
    label: Hitch Type

  additional_specs:
    type: array
    label: Additional Specifications
    options:
      add_button_label: Add specification
      structures:
        - label: Specification
          values:
            spec_title:
              type: text
              label: Specification Title
            spec:
              type: text
              label: Specification

  highlighted_features:
    type: array
    label: Highlighted Features
    options:
      add_button_label: Add feature
      type: text
      placeholder: e.g. 13ft 8in Short Wall

  trailer:
    type: array
    label: Trailer Features
    options:
      add_button_label: Add feature
      type: text
      placeholder: e.g. Stud Divider

  living_quarters:
    type: array
    label: Living Quarter Features
    options:
      add_button_label: Add feature
      type: text
      placeholder: e.g. Leather Sofa

  gallery:
    type: array
    label: Images
    options:
      add_button_label: Add image
      structures:
        - label: Image
          values:
            image:
              type: image
              label: Image

  video:
    type: array
    label: Video
    options:
      add_button_label: Add video
      structures:
        - label: Video
          values:
            url:
              type: url
              label: Video URL
            thumb:
              type: image
              label: Thumbnail

  vin:
    type: text
    label: VIN Number
  color:
    type: text
    label: Trailer Color
  thumb:
    type: image
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
  featured:
    type: switch
    label: Feature on Home Page
  Image:
    type: image

_select_data:
  jekyll-archives:
    layout: archive
    enabled: []
    permalinks:
      year: /:year/
      month: /:year/:month/
      day: /:year/:month/:day/
      tag: /tag/:name/
      category: /category/:name/

source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true

timezone: America/Chicago
